prgrms-web-devcourse-final-project/WEB2_3_Wooamo_BE

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/dto/BoardResponse.java
- src/main/java/com/api/stuv/domain/board/entity/Board.java
- src/main/java/com/api/stuv/domain/board/entity/BoardType.java
- src/main/java/com/api/stuv/domain/board/entity/Comment.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepository.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryCustom.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
- src/main/java/com/api/stuv/global/response/PageResponse.java
- 게시판 목록을 조회합니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #6 
- 전체 게시판 목록을 조회 할 수 있습니다
- 게시물의 제목에 대해 검색이 가능합니다
- 페이지 네이션 가능합니다
- 페이지 네이션에 에러로직 추가되었습니다
- 이미지 다운로드 부분은 TODO로 남겨놨습니다. 나중에 수정해주세요!
> [#6] 게시판 목록 조회

- src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
- src/main/java/com/api/stuv/domain/image/service/S3ImageService.java
- src/main/java/com/api/stuv/domain/shop/controller/CostumeController.java
- src/main/java/com/api/stuv/domain/shop/dto/CostumeListResponse.java
- src/main/java/com/api/stuv/domain/shop/dto/CostumeResponse.java
- src/main/java/com/api/stuv/domain/shop/entity/Costume.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepository.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
- 등록된 코스튬 목록 조회 기능 입니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #19 
- S3에 등록된 코스튬 이미지 목록 조회
> [#19] 코스튬 목록 조회 구현

- src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/image/exception/ImageFileNameNotFound.java
- src/main/java/com/api/stuv/domain/image/service/S3ImageService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 관리자에서의 코스튬 삭제 기능 구현했습니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #37 
- s3에 저장된 이미지 삭제
- costume, imagefile 테이블 내 데이터 삭제
- costume 예외 처리 경우, 코스튬 수정 병합 후 추가할 예정입니다
> [#37] 코스튬 삭제 기능 구현

- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/board/entity/Board.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/image/entity/EntityType.java
- src/main/java/com/api/stuv/domain/image/entity/ImageFile.java
- src/main/java/com/api/stuv/domain/image/service/ImageService.java
- src/main/java/com/api/stuv/domain/image/service/S3ImageService.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
- 게시글 등록에 다중 이미지 적용했습니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #49 
- 게시글에 등록시, S3에 다중 이미지 등록 가능합니다 
- 이미지 엔티티 entityId 추가
- handleImage 공통 메서드 적용
> [#49] 게시글 이미지 등록 기능 추가 구현

- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryCustom.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/image/service/ImageService.java
- 게시글 목록 조회 이미지 처리 추가 기능입니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #56 
- 목록 조회시, 가장 처음의(오래된) 이미지 url 반환
> [#56] 게시글 목록조회 이미지 추가 구현

- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- 게시글 상세 조회 이미지 반환
- 이 PR 이 해결하려는 관련 이슈 번호 : #65 
- 게시글 상세조회에 대한 다중이미지 반환
> [#65] 게시글 상세조회 이미지 추가 구현

- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/image/repository/ImageFileRepository.java
- 게시글 삭제시 이미지 또한 삭제 됩니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #70 
- DB에 저장된 이미지 내용 삭제
- S3에 저장된 이미지 내용 삭제
> [#70] 게시글 삭제에서 이미지 삭제 추가 구현

- src/main/java/com/api/stuv/domain/image/entity/EntityType.java
- src/main/java/com/api/stuv/domain/user/dto/response/MyInformationResponse.java
- src/main/java/com/api/stuv/domain/user/dto/response/UserInformationResponse.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- 사용자 정보 조회에 이미지 정보를 추가하였습니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #79 
- 나의 이미지 정보 조회
- 남의 이미지 정보 조회
> [#79] 사용자 이미지 정보 조회 추가 구현

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/dto/response/UserBoardListResponse.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 본인이 작성한 글 목록(제목, 내용, 타입, 사진)을 볼 수 있다
- 이 PR 이 해결하려는 관련 이슈 번호 : #108 
- board 테이블에 저장된 게시글과 images_file 테이블에 있는 이미지 파일을 결합해
- 목록으로 반환
> [#108] 본인 작성글 조회 기능 구현

- src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
- src/main/java/com/api/stuv/domain/admin/dto/request/ConfirmRequest.java
- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/party/entity/GroupMember.java
- src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
- src/main/java/com/api/stuv/global/exception/ValidationException.java
- 회원의 날짜별 팟 인증에 대한 상태 변경 기능 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #110 
- 회원의 날짜별 팟 인증에 대한 상태 변경 기능 구현
- 회원의 팟 퀘스트 성공 여부 체크
- 팟의 인증 완료 여부 체크
> [#110] 회원의 날짜별 팟 인증에 대한 상태 변경 기능 구현

- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
- src/main/java/com/api/stuv/domain/socket/dto/ChatMessageResponse.java
- src/main/java/com/api/stuv/domain/socket/dto/ChatRoomResponse.java
- src/main/java/com/api/stuv/domain/socket/dto/ReadByResponse.java
- src/main/java/com/api/stuv/domain/socket/entity/ChatMessage.java
- src/main/java/com/api/stuv/domain/socket/entity/ChatRoom.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepository.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryCustom.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryImpl.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatRoomRepository.java
- src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- 채팅방 목록 및 페이징 응답 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #162 
- `ChatMessageService`에서 `ChatRoomDetailService`로 채팅방 조회 서비스 이동  
- 각 채팅방의 마지막 메시지와 전송 시간을 함께 반환  
- 최신 메시지를 기준으로 채팅방 목록 정렬  
- PRIVATE - 마지막 메시지 보낸 사용자의 프로필 이미지 및 닉네임 추가  
- GROUP - 그룹명과 마지막 메시지 반환  
- 사용자가 읽지 않은 메시지 개수(`unreadCount`) 표시  
- 새 메시지가 전송될 때마다 웹소켓 실시간으로 채팅 목록 업데이트  
- 구독자 체크 - 채팅 목록 페이지에 접속한 사용자가 없는 경우 불필요한 서비스를 실행하지 않음
> [#162] 채팅방 목록 및 페이징 응답 수정

- src/main/java/com/api/stuv/domain/party/controller/PartyController.java
- src/main/java/com/api/stuv/domain/party/dto/response/PartyDetailResponse.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- 팟 상세 정보 조회 (자신의 참가여부 포함) 기능
- 이 PR 이 해결하려는 관련 이슈 번호 : #229 
- 팟 상세 정보 조회 (자신의 참가여부 포함) 기능
> [#229] 팟 상세 정보 조회 (자신의 참가여부 포함) 기능

- src/main/java/com/api/stuv/domain/party/controller/PartyController.java
- src/main/java/com/api/stuv/domain/party/dto/MemberDTO.java
- src/main/java/com/api/stuv/domain/party/dto/response/EventBannerResponse.java
- src/main/java/com/api/stuv/domain/party/dto/response/MemberResponse.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- src/main/java/com/api/stuv/domain/user/entity/UserStatus.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
- 팟 참여자 목록 조회 및 이벤트 배너 조회 기능 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #243 
- 팟 참여자 목록 조회 기능
- 이벤트 배너 조회 기능
- 월간 공부시간 조회 API 접근 방식 변경
> [#243] 팟 참여자 목록 조회 및 이벤트 배너 조회 기능 구현

- src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
- src/main/java/com/api/stuv/domain/admin/dto/response/PointSalesResponse.java
- src/main/java/com/api/stuv/domain/admin/dto/response/WeeklyInfoResponse.java
- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/image/dto/ImageDTO.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/shop/repository/PaymentRepository.java
- src/main/java/com/api/stuv/domain/shop/repository/PaymentRepositoryCustom.java
- src/main/java/com/api/stuv/domain/shop/repository/PaymentRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- 관리자 주간 정보 조회 및 최근 매출 내역 조회
- 이 PR 이 해결하려는 관련 이슈 번호 : #256 
- 관리자 주간 정보 조회
- 최근 매출 내역 조회
- 팟 인증 사진 조회 기능 버그 픽스
> [#256] 관리자 주간 정보 조회 및 최근 매출 내역 조회

- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/dto/ChatRoomInfoResponse.java
- src/main/java/com/api/stuv/domain/socket/dto/ChatRoomResponse.java
- src/main/java/com/api/stuv/domain/socket/dto/GroupInfo.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
- 채팅방 멤버 정보 전송 및 응답 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #291 
- 타이틀별 채팅방 정보 조회 서비스 추가 및 GroupInfo 레코드 추가
- 그룹 채팅룸 id 등록 변경
> [#291] 채팅방 멤버 정보 전송 및 응답 수정

- src/main/java/com/api/stuv/domain/alert/service/AlertService.java
- src/main/java/com/api/stuv/domain/party/dto/response/PartyDetailResponse.java
- src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepository.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- src/main/java/com/api/stuv/domain/shop/repository/PaymentRepositoryImpl.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #303 
- 팟 상세에 isAuth 항목 추가
- 팟 상세 중복 인증에 대한 예외처리 확인
- 시작전인 팟 목록 시작일이 빠른 순서대로 정렬
- 참여중인 팟 목록 마감일이 빠른 순서대로 정렬
- 관리자 포인트 결제 이력 최신순 정렬 및 10개 데이터 제한
- 관리자 팟 관리 목록 시작일 기준으로 오래된 순 정렬
> [#303] 팟 및 관리자 기능 핫픽스, 일부 출력문 제거

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
- src/main/java/com/api/stuv/domain/socket/dto/ChatRoomTypeInfoResponse.java
- src/main/java/com/api/stuv/domain/socket/dto/UserInfoWithContext.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
-채팅방 1:1방, 그룹방 정보 응답 오류 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #308 
- UserInfo와 UserInfoWithContext 분리 및 context 추가
- PRIVATE 채팅방에서 사용자 정보를 조회할 때 context 포함 여부에 따라 적절한 record 사용
- GROUP 채팅방에서는 본인의 정보를 포함하여 응답하도록 변경
- getChatRoomInfoByRoomName에서 PRIVATE 채팅방의 경우 UserInfoWithContext를 활용하여 context 추가
> [#308]: 채팅방 1:1방, 그룹방 정보 응답 오류 수정

- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
- Board 및 코멘트 가져올 때 순서 createdAt 으로 정렬
- 이 PR 이 해결하려는 관련 이슈 번호 : #313 
- Board 및 코멘트 가져올 때 순서 createdAt 으로 정렬
> [#313] 코멘트 순서 수정

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryCustom.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryImpl.java
- src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
- 채팅 메시지 페이징 조회 개선 및 중복 조회 방지
- 이 PR 이 해결하려는 관련 이슈 번호 : #316 
- ChatMessageRepository 생성 및 페이징 메시지 조회 쿼리 추가
- ChatController에 메시지 조회 API 수정
- 메시지 조회 시 중복된 `UserInfo` 조회 방지
> [#316] 메세지 불러오기 페이지네이션 수정

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryCustom.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryImpl.java
- src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
- 읽음 상태 업데이트 소켓 통신 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #340 
- /chat/read 삭제 후 /chat/join으로 병합
- /topic/read/ 응답은 userId로 변경
- 특정 메세지까지 조회하는 /{roomId}/messages/until 추가
- getMessagesUntilLastChatId 서비스 추가
> [#340] 읽음 상태 업데이트 소켓 통신 변경

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 코스튬 변경 시 ChatRoomMemberService의 Redis 캐시 업데이트
- 이 PR 이 해결하려는 관련 이슈 번호 : #347 
- changeUserCostume() 실행 시 변경된 프로필 URL을 Redis에 반영
- ChatRoomMemberService에 updateUserProfileInCache() 추가하여 캐시 업데이트
- 기존 UserInfo 조회 후 프로필 정보만 변경하여 Redis에 저장
> [#347] 코스튬 변경 시 채팅방 프로필 변경

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
- lastChatId가 null이거나 메시지가 없을 때 빈 배열 반환
- 이 PR 이 해결하려는 관련 이슈 번호 : #354 
- getMessagesUntilLastChatId()에서 lastChatId가 null이면 빈 리스트 반환
- findMessagesUntilLastChatId()에서 조회된 메시지가 없을 경우 빈 리스트 반환
> [#354] 채팅방 메시지 범위 조회 응답 예외 처리

- src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
- src/main/java/com/api/stuv/domain/auth/jwt/JWTFilter.java
- src/main/java/com/api/stuv/domain/auth/jwt/JWTUtil.java
- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/auth/service/ReissueService.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- src/main/java/com/api/stuv/global/config/SecurityConfig.java
- 이전에 로그인했던 사용자의 access 토큰을 블랙리스트에 올려 재접근을 막는 기능 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #353 
- 로그아웃 시 access 토큰의 만료 기간이 아직 남아있다면 redis에 저장해 재접근하지 못하도록 함
- access, refresh 토큰의 만료기간 10분, 1일에서 1시간, 7일로 변경
> [#353] 로그인 access토큰 블랙리스트 설정
