- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/entity/Friend.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/test/java/com/api/stuv/domain/friend/service/AcceptFriendRequestTest.java
- 친구 수락 기능 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #5 
- 존재하는 친구 요청인지 확인
- 이미 수락된 친구 요청인지 확인
- friends 테이블의 status 값을 변경
> [#5] 친구 수락 기능 구현

- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/main/java/com/api/stuv/global/exception/AccessDeniedException.java
- src/main/java/com/api/stuv/global/exception/BadRequestException.java
- src/main/java/com/api/stuv/global/exception/DuplicateException.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
- src/main/java/com/api/stuv/global/exception/NotFoundException.java
- 에러 및 응답 구조 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #9
- Friend 서비스측 응답 및 에러 로직 변경
- ErrorCode 및 Exception 추가
- Exception handler 수정
> [#9] 에러 및 응답 구조 변경

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/dto/CommentResponse.java
- src/main/java/com/api/stuv/domain/board/entity/Board.java
- src/main/java/com/api/stuv/domain/board/entity/Comment.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepository.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryCustom.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/entity/Friend.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/exception/NotFoundException.java
- src/main/java/com/api/stuv/global/response/PageResponse.java
- src/test/java/com/api/stuv/domain/friend/service/AcceptFriendRequestTest.java
- 게시글내 코멘트 조회 기능
- 이 PR 이 해결하려는 관련 이슈 번호 : #18 
- Board Id 에 대한 값 검증
- 코멘트 리스트 조회
- 프로필 주소 확인 필요합니다!
> [#18] 코멘트 리스트 조회

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/entity/Comment.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- Comment 작성
- 이 PR 이 해결하려는 관련 이슈 번호 : #23 
- 유저 검증
- 게시글 ID 확인
- 코멘트 DB 저장
- TODO: 이후 알림 추가시 알림 로직 추가
- 이후 유저 ID 관련 변경
> [#23] 코멘트작성

- src/main/java/com/api/stuv/global/service/RedisService.java
- src/test/java/com/api/stuv/global/service/RedisServiceTest.java
RedisService의 find 메소드 수정 및 테스트 코드 작성
- Redis 직렬화 오류를 수정하여 JSON 데이터가 정상적으로 저장 및 조회되도록 개선
- 이 PR 이 해결하려는 관련 이슈 번호 : #33 
- 직렬화/역직렬화 에러 수정
- 직렬화/역직렬화 테스트 코드 작성
> [#33] Redis 직렬화/역직렬화 오류 핫픽스

- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/dto/FriendResponse.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- 친구 목록 조회 API
- 이 PR 이 해결하려는 관련 이슈 번호 : #32 
- 친구 목록 확인
> [#32] 친구 목록

- src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
- src/main/java/com/api/stuv/domain/admin/dto/CostumeRequest.java
- src/main/java/com/api/stuv/domain/admin/exception/CostumeNotFound.java
- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/shop/entity/Costume.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 코스튬 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #30 
- contents 수정
> [#30] 코스튬 수정 기능 구현

- src/main/java/com/api/stuv/domain/party/controller/PartyController.java
- src/main/java/com/api/stuv/domain/party/dto/response/PartyGroupResponse.java
- src/main/java/com/api/stuv/domain/party/entity/PartyGroup.java
- src/main/java/com/api/stuv/domain/party/entity/PartyStatus.java
- src/main/java/com/api/stuv/domain/party/repository/PartyGroupRepository.java
- src/main/java/com/api/stuv/domain/party/repository/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- src/main/java/com/api/stuv/global/service/RedisService.java
- src/test/java/com/api/stuv/domain/party/repository/PartyGroupRepositoryImplTest.java
- 팟 목록 조회 API 작성 (1)
- 이 PR 이 해결하려는 관련 이슈 번호 : #8 
- [팟] 시작 예정 팟 목록 조회 (검색 기능 포함)
- [팟] 현재 사용자의 참여중인 팟 목록 조회
> [#8] 팟 목록 조회 - 시작 예정, 참여중

- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/shop/controller/CostumeController.java
- src/main/java/com/api/stuv/domain/shop/dto/CostumeResponse.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
- 코스튬 상세조회 기능 구현입니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #41 
- 코스튬 id 값에 따른 상세조회
> [#41] 코스튬 상세조회 기능 구현

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/dto/BoardDetailResponse.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryCustom.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- 게시판 상세 조회API
-
- 이 PR 이 해결하려는 관련 이슈 번호 : #31
- 게시판 상세조회
- 게시판 여부 확인
- 코스튬 여부 확인
- 게시판 파일 이미지 불러오기 -> TODO
> [#31] 게시판 상세 조회

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/entity/Board.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/test/java/com/api/stuv/domain/board/service/ConfirmCommentTest.java
- 답변 채택 API
- 이 PR 이 해결하려는 관련 이슈 번호 : #46 
- 답변 존재 확인
- 게시글 존재 확인
- 게시글에 이미 채택된 답변이 있는지 확인
- 게시글을 쓴 사람이 맞는지 확인
- 답변 채택
- 알림기능 추후에 넣겠습니다. TODO에 적어놨습니다.
> [#46] 답변 채택

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 친구 삭제 API
- 이 PR 이 해결하려는 관련 이슈 번호 : #48
- 친구 삭제 API
- 친구쪽 - userId Token 에서 가져오도록 수정
- 게시판쪽 - 유저 유무 검증 삭제
> [#48] 친구 삭제

- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/dto/FriendSearchResponse.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- 유저 검색 API
- 이 PR 이 해결하려는 관련 이슈 번호 : #53
- query 문을 통해 친구 검색
- 페이징 처리
- profile 얻기 구현 완료
> [#53] 친구 검색

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/dto/response/MyInformationResponse.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 본인 정보를 조회한다
- 이 PR 이 해결하려는 관련 이슈 번호 : #57 
- 내 id, 자기소개, 링크, 닉네임, 포인트, 프로필사진을 가져온다
> [#57] 본인 정보 조회 

- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- 친구 추천 API
- 이 PR 이 해결하려는 관련 이슈 번호 : #61 
- 친구 랜덤 추천
- 현재 친구 요청 및 친구 상태인 유저 제외
- 프로필 불러오기 우선은 만들어 놨는데 검토만 부탁드려요
> [#61] 친구 추천

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepository.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/image/repository/ImageFileRepository.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 게시글 삭제 API
- 이 PR 이 해결하려는 관련 이슈 번호 : #55 
- 게시글 유무 확인
- 게시글에 대한 권한 확인
- 이미지 삭제
- 코멘트 삭제
- 게시글 삭제
- 이미지 삭제에 대한 처리 부탁드립니다
> [#55] 게시글 삭제

- src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/image/repository/ImageFileRepository.java
- src/main/java/com/api/stuv/domain/shop/entity/Costume.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- 테이블 변경에 따른 코스튬 리팩토링 입니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #72 
- 코스튬 등록, 삭제에 대한 리팩토링 진행했습니다
> [#72] 코스튬 리팩토링

- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/user/entity/User.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/test/java/com/api/stuv/domain/board/service/ConfirmCommentTest.java
- 답변 채택 및 삭제 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #75 
- 답변 채택시 답변 작성자에게 50 포인트 부여
- 채택된 답변은 삭제 불가 처리
- 채택에 대한 테스트 코드 일부 변경
- 채택시 부여되는 포인트는 이후 변경
> [#75] 답변 채택 및 삭제 수정

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/dto/BoardUpdateRequest.java
- src/main/java/com/api/stuv/domain/board/entity/Board.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- 게시글 수정 API
- 이 PR 이 해결하려는 관련 이슈 번호 : #74 
- 게시글 수정
- TODO 에 이미지 파일 남은 부분 적어뒀어요
> [#74] 게시글 수정

- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/dto/FriendResponse.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- 친구 리스폰스 및 리퀘스트 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #87 
- Response 및 Request 수정
- 일부 로직 수정
> [#87] 친구 리스폰스 및 리퀘스트 수정

- src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- 응답 처리, 누락사항 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #86 
- 로그인, 로그아웃 시 공통 응답으로 반환하게 함
- 코드리뷰 시 받았던 피드백 중 누락 사항 수정
> [#86] 응답 처리 및 누락 사항 수정

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/dto/request/AddTodoRequest.java
- src/main/java/com/api/stuv/domain/user/dto/response/AddTodoResponse.java
- src/main/java/com/api/stuv/domain/user/entity/TodoList.java
- src/main/java/com/api/stuv/domain/user/service/TodoService.java
- todo리스트 추가 api 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #85 
- todo리스트 입력 받아 DB에 저장
> [#85] todo리스트 추가 기능 구현

- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #77 
- Response 및 Request 수정
- 프로필 Url 수정
> [#77] 프로필 Url 수정

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/dto/response/GetTodoListResponse.java
- src/main/java/com/api/stuv/domain/user/repository/TodoListRepository.java
- src/main/java/com/api/stuv/domain/user/service/TodoService.java
- 자신의 투두리스트를 조회함
- 
- 이 PR 이 해결하려는 관련 이슈 번호 : #94 
- 사용자가 작성한 todo리스트를 db에서 가져와 리스트로 반환
> [#94] todo리스트 조회 기능 구현

- src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
- src/main/java/com/api/stuv/domain/admin/dto/MemberDetailDTO.java
- src/main/java/com/api/stuv/domain/admin/dto/request/CostumeRequest.java
- src/main/java/com/api/stuv/domain/admin/dto/response/AdminPartyAuthDetailResponse.java
- src/main/java/com/api/stuv/domain/admin/dto/response/AdminPartyGroupResponse.java
- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepository.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/global/exception/DateOutOfRangeException.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/test/java/com/api/stuv/domain/admin/service/AdminServiceTest.java
잘못된 기간에 대한 예외처리 및 Not Found 예외처리 완료
- 팟 인증 상세 조회 기능 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #90 
- Not Found 예외 처리
- Invalid Date 예외 처리 ( 범위를 벗어난 날짜를 입력 시 )
- RequestParam에 대한 초기 값이 없을 때 팟의 startDate를 적용
- 팟 인증에 대한 상세 조회
> [#90] 팟 인증 상세 조회 기능 구현

- src/main/java/com/api/stuv/domain/user/service/TodoService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/util/email/TodoListScheduler.java
- todo리스트를 작성한 다음날이 되면 todo리스트 삭제
- todo리스트 crud api 내 에러 처리
- 이 PR 이 해결하려는 관련 이슈 번호 : #102
> [#102] todo 리스트 스케쥴링 및 에러처리

- src/main/java/com/api/stuv/domain/board/dto/BoardResponse.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- 게시글 Response 필드 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #111 
- 
- 게시글 Response 필드에 context 추가
> [#111] 게시글 Response 필드 추가

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/dto/BoardUpdateRequest.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- 게시글 수정에 대한 다중 이미지 처리
- 이 PR 이 해결하려는 관련 이슈 번호 : #83 
- 다중이미지 처리
> [#83] 게시글 수정 이미지 처리

- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepository.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 게시판 및 친구 일부 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #118 
- 코멘트 생성 userId, boardId 가 반대로 들어가는 것 수정
- 게시글 수정 if 문 추가
- 친구 자기 자신에게 신청 에러 추가
- 친구 요청 중복에 대한 에러 일부 수정
- 친구 삭제 조건 일부 수정
> [#118] 게시판 및 친구 일부 수정

- src/main/java/com/api/stuv/domain/socket/entity/ChatMessage.java
- 소켓 관련 에러 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #123 
- ChatMessage 엔티티 내부의 `@Builder` 관련 에러 수정
> [#123] Socket Error Fix

- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- API 명세서와 다른 부분 및 정상 작동하지 않는 코드 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #122
- 로그인 POST 메소드일때만 실행되게 변경
- 작성글 조회 레포지토리(이미지 불러오기) 수정
> [#122] 에러 사항 수정

- src/main/java/com/api/stuv/global/config/S3Config.java
- src/main/resources/application.yml
- s3 배포를 위한 수정입니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #128 
- s3 config
- yml
> [#128] s3 config 수정

- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryCustom.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- Board 서비스 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #130 
- Board 서비스 수정
> chron: Board 서비스 수정

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/entity/HistoryType.java
- src/main/java/com/api/stuv/domain/user/entity/PointHistory.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 개인 퀘스트 조건을 만족하면 보상을 받을 수 있다
- 이 PR 이 해결하려는 관련 이슈 번호 : #127 
- 오늘 공부 시간이 퀘스트 조건에 만족하는지 확인한다
- 이미 개인 퀘스트 보상을 받았는지 확인한다
- 문제 없다면 오늘 퀘스트에 대한 보상을 저장한다
> [#127] 개인 퀘스트 보상 받기 기능 구현

- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- 사용자가 가지고 있는 코스튬 불러오기
- 이 PR 이 해결하려는 관련 이슈 번호 : #133 
- u.costumeId = uc.id
- uc.costumeId = c.id
- 고려해서 u.costumeId 부분 수정했습니다
> [#133] 코스튬 정보 불러오기 수정

- src/main/java/com/api/stuv/global/config/SecurityConfig.java
- src/main/resources/application.yml
- CORS 에러 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #138 
- CORS Error fix
> [#138] SecurityConfig CORS 수정

- src/main/java/com/api/stuv/domain/auth/jwt/JWTFilter.java
- src/main/java/com/api/stuv/domain/auth/util/TokenUtil.java
- src/main/java/com/api/stuv/global/exception/InvalidUserRoleException.java
- src/main/java/com/api/stuv/global/exception/UserNotAuthenticatedException.java
- 토큰과 사용자 역할에 대한 예외 처리 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #140 
- 토큰과 사용자 역할에 대한 예외 처리 추가
> [#140] 토큰과 사용자 역할에 대한 예외 처리 추가

- Dockerfile
- jar에 대한 경로 수정입니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #143 
- 경로 * 수정
> [#143] Dockerfile 경로 수정

- src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
- src/main/java/com/api/stuv/domain/timer/dto/response/TimerListResponse.java
- src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepository.java
- src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryCustom.java
- src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 저장되어있는 타이머 리스트 조회
- 이 PR 이 해결하려는 관련 이슈 번호 : #137 
- 저장되어있는 타이머들 목록 반환
> [#137] 타이머 조회 기능 구현

- src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
- src/main/java/com/api/stuv/domain/timer/repository/TimerRepository.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 타이머 카테고리 삭제 기능 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #147 
- 타이머 카테고리에 저장되어있는 카테고리만 삭제
> [#147] 타이머 카테고리 삭제 기능 구현

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/dto/response/GetCostume.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 사용자가 가지고 있는 코스튬 목록을 조회한다
- 이 PR 이 해결하려는 관련 이슈 번호 : #155
- userId로 코스튬 목록을 받는다
- 이미지 파일을 링크로 변환해 받는다
> [#155] 코스튬 조회 기능 구현

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
- src/main/java/com/api/stuv/domain/socket/dto/ChatMessageResponse.java
- src/main/java/com/api/stuv/domain/socket/dto/ReadByResponse.java
- src/main/java/com/api/stuv/domain/socket/entity/ChatMessage.java
- src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
- 채팅 메시지 응답 구조 개선 및 날짜 포맷 적용
- 이 PR 이 해결하려는 관련 이슈 번호 : #126 
- 날짜 데이터 포맷 적용
- 채팅 메시지 응답 구조 변경 및 읽지 않은 메시지 수 계산 추가
> [#126] 채팅 메시지 응답 구조 개선 및 날짜 포맷 적용

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- src/main/resources/application.yml
- 회원가입, 로그인 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #161 
- 회원가입 후 바로 로그인되게 설정
- 로그인 후 메인페이지로 리다이렉션 설정
> [#161] 카카오 로그인 기능 수정

- src/main/java/com/api/stuv/global/config/SecurityConfig.java
- Access-Control-Allow-Header에 access header가 들어갈 수 있도록 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #167
> [#167] cors 관련 핫픽스

- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
- src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
- src/main/java/com/api/stuv/domain/timer/dto/request/StudyTimeRequest.java
- src/main/java/com/api/stuv/domain/timer/dto/response/TimerListResponse.java
- src/main/java/com/api/stuv/domain/timer/entity/StudyTime.java
- src/main/java/com/api/stuv/domain/timer/entity/StudyTimeId.java
- src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepository.java
- src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryCustom.java
- src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/timer/repository/TimerRepository.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/service/RedisService.java
- src/main/java/com/api/stuv/global/util/common/TemplateUtils.java
- src/main/java/com/api/stuv/global/util/scheduler/TimerScheduler.java
- src/main/java/com/api/stuv/global/util/scheduler/TodoListScheduler.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #154 
- 공부 시간 저장 기능 구현 (레디스 Hash Set 사용)
- 10분마다 백업 스케쥴러 (Redis -> MariaDB)
- 00시마다 디비에 저장 및 레디스 데이터 삭제 (Redis -> MariaDB)
- 공부시간 타입이 Time 에서 BigInt로 바뀜에 따라 기존 기능 리팩토링
> [#154] 자신의 공부 시간 저장 기능 구현 With Redis

- src/main/java/com/api/stuv/domain/user/dto/response/MyInformationResponse.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/resources/application.yml
- 현재 로그인한 회원 정보의 응답에 role 추가해서 반환
- 
- 이 PR 이 해결하려는 관련 이슈 번호 : #166 
> [#166] user 정보 반환 변경

- .github/workflows/cd.yml
- 자동 배포 문제 해결을 위한 기능입니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #132 
- 자동 배포
> [#132] cd 버전 변경

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/dto/response/ChangeUserCostume.java
- src/main/java/com/api/stuv/domain/user/entity/User.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 사용자 아바타의 코스튬을 변경한다
- 이 PR 이 해결하려는 관련 이슈 번호 : #157 
- user db의 코스튬 아이디를 변경하고 새로운 이미지를 링크로 반환한다
> [#157] 코스튬 변경 기능 구현

- src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
- src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- 쿠키 설정 samesite=none으로 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #174 
> [#174] 쿠키 설정 핫픽스

- src/main/java/com/api/stuv/global/config/CookieConfig.java
> [#176] cookie fix

- src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- src/main/java/com/api/stuv/global/config/SecurityConfig.java
- src/main/resources/application.yml
- cookie 설정 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : 
> [hotfix] cookie 설정 변경

- .github/workflows/cd.yml
- 배포 파일 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #185 
- 자동 배포 되지 않는 문제 해결을 위한 수정
> [#185] cd 파일 수정

- .github/workflows/cd.yml
- 배포 파일 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #185
- 현재 브랜치 업데이트
> [#185] 배포 파일 수정

- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/global/config/SecurityConfig.java
- src/main/resources/application.yml
- access token 제한시간 연장
- 이 PR 이 해결하려는 관련 이슈 번호 : fix
- access token 제한시간 연장
> [fix] access token 제한시간 연장

- src/main/java/com/api/stuv/domain/board/dto/BoardDetailResponse.java
- src/main/java/com/api/stuv/domain/timer/controller/TimerController.java
- src/main/java/com/api/stuv/domain/timer/dto/request/AddTimerCategoryRequest.java
- src/main/java/com/api/stuv/domain/timer/dto/response/AddTimerCategoryResponse.java
- src/main/java/com/api/stuv/domain/timer/dto/response/AddTimerCatetoryResponse.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- src/main/java/com/api/stuv/domain/user/dto/response/UserBoardListResponse.java
- src/main/java/com/api/stuv/global/response/PageResponse.java
- 프론트 요청사항 핫픽스
- 이 PR 이 해결하려는 관련 이슈 번호 : fix
- 프론트 요청사항 핫픽스
> [fix] 프론트 요청사항 핫픽스

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/dto/CommentRequest.java
- 프론트 요청사항 핫픽스
- 이 PR 이 해결하려는 관련 이슈 번호 : fix
- 프론트 요청사항 핫픽스
> [fix] 코멘트 추가 API 요청에 대한 항목 수정

- .github/workflows/cd.yml
> fix: docker compose 수정

- src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
- src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #191
> [#191] cookie 설정 변경

- src/main/java/com/api/stuv/domain/shop/controller/ShopController.java
- src/main/java/com/api/stuv/domain/shop/dto/CostumeRandomRequest.java
- src/main/java/com/api/stuv/domain/shop/dto/CostumeRandomResponse.java
- src/main/java/com/api/stuv/domain/shop/exception/CostumeNotPurchaseException.java
- src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
- src/main/java/com/api/stuv/domain/user/entity/User.java
- src/main/java/com/api/stuv/domain/user/repository/UserCostumeRepository.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 코스튬 랜덤 구매 기능입니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #200 
- 코스튬 랜덤 구매
> [#200] 코스튬 랜덤 구매

- src/main/java/com/api/stuv/domain/auth/controller/ReissueController.java
- src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- cookie 설정 핫픽스
- 이 PR 이 해결하려는 관련 이슈 번호 : 
> [hotfix] cookie 설정 핫픽스

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- 메서드 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #208
> [#208] 코스튬 변경 기능 수정

- src/main/java/com/api/stuv/domain/timer/dto/UserRankDTO.java
- src/main/java/com/api/stuv/domain/timer/dto/response/RankInfoResponse.java
- src/main/java/com/api/stuv/domain/timer/dto/response/RankResponse.java
- src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryCustom.java
- src/main/java/com/api/stuv/domain/timer/repository/StudyTimeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/dto/UserProfileInfoDTO.java
- src/main/java/com/api/stuv/domain/user/entity/HistoryType.java
- src/main/java/com/api/stuv/domain/user/entity/RewardType.java
- src/main/java/com/api/stuv/domain/user/entity/User.java
- src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepository.java
- src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/global/util/initializer/ApplicationInitializer.java
- src/main/java/com/api/stuv/global/util/scheduler/TimerScheduler.java
- src/main/java/com/api/stuv/global/util/scheduler/TodoListScheduler.java
- 주간 공부시간 랭킹 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #202 
- 회원의 주간 공부시간 랭킹 조회
- 전체 주간 공부시간 랭킹 중 1~3등 조회
- 매주 일요일 00시마다 상위권 3명에게 보상 스케쥴링
> [#202] 주간 공부시간 랭킹 구현

- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- Board 서비스 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #213 
- Board 서비스 수정
> [#213] Board 서비스 수정

- docker-compose.yml
- time zone 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #216 
- 도커 파일 내 타임존 설정 추가
> [#216] docker-compose time zone 수정

- src/main/java/com/api/stuv/domain/user/entity/TodoList.java
- todo 수정 시 체크 값이 들어오지 않는다면 false로 저장되도록 디폴트 값 설정
- 이 PR 이 해결하려는 관련 이슈 번호 : #218
> [#218] todo isChecked 디폴트값 설정

- src/main/java/com/api/stuv/domain/timer/dto/response/RankInfoResponse.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- 일일 총 공부시간 -> 마리아디비에서 레디스로 조회방식 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #215 
- 일일 총 공부시간 -> 마리아디비에서 레디스로 조회방식 변경
> [#215] 일일 총 공부시간 -> 마리아디비에서 레디스로 조회방식 변경

- src/main/java/com/api/stuv/domain/user/dto/response/UserInformationResponse.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #221
> [#221] user API 수정

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/entity/ChatRoom.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepository.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatRoomRepository.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 개인방 및 그룹방 채팅 생성, 업데이트, 삭제
- 이 PR 이 해결하려는 관련 이슈 번호 : #212 
- 개인 및 그룹 채팅방 생성 추가  
- 그룹 채팅방 인원 추가 구현  
- 그룹 채팅방 삭제 추가  
- 그룹 채팅방 최대 인원 설정 추가
- 그룹 채팅방 삭제 시 관련 메시지 삭제 추가
> [#212] 개인방 및 그룹방 채팅 생성, 업데이트, 삭제

- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- profile url 에 null 이 포함되는 경우 null 값 출력
- 이 PR 이 해결하려는 관련 이슈 번호 : #224 
- user profile null 해결
> [#224] profile 없는 경우 null 출력

- src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
- src/main/java/com/api/stuv/domain/shop/service/PaymentService.java
- 포인트 충전 및 사용에 대한 history 저장 기능 추가했습니다
- 이 PR 이 해결하려는 관련 이슈 번호 : #226
- 포인트 사용시, 사용 기록 저장
- 포인트 충전시, 충전 기록 저장
> [#226] 포인트 내역 저장

- src/main/java/com/api/stuv/domain/party/controller/PartyController.java
- src/main/java/com/api/stuv/domain/party/dto/MemberRewardStatusDTO.java
- src/main/java/com/api/stuv/domain/party/dto/response/PartyRewardStatusResponse.java
- src/main/java/com/api/stuv/domain/party/entity/QuestStatus.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- 마감된 팟 목록 조회 (보상 획득 여부, 포인트, 성공여부)
- 이 PR 이 해결하려는 관련 이슈 번호 : #152 
- 마감된 팟 목록 조회 (보상 획득 여부, 포인트, 성공여부)
> [#152] 마감된 팟 목록 조회 (보상 획득 여부, 포인트, 성공여부)

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- 소셜로그인 응답 주소 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #233 
- 소셜로그인 응답 주소 변경
> [#233] 소셜로그인 응답 주소 변경

- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/dto/AddUserToGroupChatRequest.java
- src/main/java/com/api/stuv/domain/socket/dto/ChatRoomResponse.java
- src/main/java/com/api/stuv/domain/socket/dto/CreateGroupRoomRequest.java
- src/main/java/com/api/stuv/domain/socket/dto/CreatePrivateRoomRequest.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 응답 수정 및 에러 코드 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #230 
- 그룹 채팅방 조회 시 불필요한 groupName 조회 로직 제거
- ChatRoomResponse에서 groupName 필드 제거
- POST 요청에서 @RequestBody 적용
- CHAT SOCKET ErrorCode 수정
> [#230] 응답 수정 및 에러 코드 수정

- src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
- 랜덤 구매 후, 코스튬 이름 반환
- 이 PR 이 해결하려는 관련 이슈 번호 : #236 
- 코스튬 이름 반환 수정입니다
> [#236] 구매 후 코스튬 이름 반환

- src/main/java/com/api/stuv/domain/alert/controller/AlertController.java
- src/main/java/com/api/stuv/domain/alert/controller/SseController.java
- src/main/java/com/api/stuv/domain/alert/dto/AlertResponse.java
- src/main/java/com/api/stuv/domain/alert/entity/Alert.java
- src/main/java/com/api/stuv/domain/alert/entity/AlertType.java
- src/main/java/com/api/stuv/domain/alert/repository/AlertRedisRepository.java
- src/main/java/com/api/stuv/domain/alert/service/AlertService.java
- src/main/java/com/api/stuv/domain/alert/service/SseService.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/main/java/com/api/stuv/global/config/RedisConfig.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/exception/GlobalExceptionHandler.java
- src/main/java/com/api/stuv/global/exception/JsonParseException.java
- src/main/java/com/api/stuv/global/exception/SseErrorException.java
- src/main/java/com/api/stuv/global/service/RedisPublisher.java
- src/main/java/com/api/stuv/global/service/RedisService.java
- src/main/java/com/api/stuv/global/service/RedisSubscriber.java
- src/main/java/com/api/stuv/global/util/common/TemplateUtils.java
- src/test/java/com/api/stuv/domain/board/service/ConfirmCommentTest.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #66
- 알림 목록 조회
- 알림 전체 읽음 처리
- 특정 알림 읽음 처리
- SSE 연결
- SSE 연결 해제
> [#66] 알림 기능 기초적으로 완성

- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/dto/response/MyInformationResponse.java
- src/main/java/com/api/stuv/domain/user/dto/response/UserInformationResponse.java
- src/main/java/com/api/stuv/domain/user/repository/UserCostumeRepository.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryCustom.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- API 상 버그 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #238 
- 개인 퀘스트 보상 포인트 ENUM으로 수정
- 타인 정보 조회 시 친구 수
- 나의 정보 조회 시 친구 수
- 프로필 변경 후 profile null 값 들어가는 문제
> [#238] 버그 사항 수정

- src/main/java/com/api/stuv/domain/party/controller/PartyController.java
- src/main/java/com/api/stuv/domain/party/dto/request/PartyCreateRequest.java
- src/main/java/com/api/stuv/domain/party/dto/request/PartyJoinRequest.java
- src/main/java/com/api/stuv/domain/party/dto/response/PartyIdResponse.java
- src/main/java/com/api/stuv/domain/party/entity/GroupMember.java
- src/main/java/com/api/stuv/domain/party/entity/PartyGroup.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- src/main/java/com/api/stuv/domain/timer/service/TimerService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- 팟 생성 및 참가 기능 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #232 
- 팟 생성 및 참가 기능 구현
> [#232] 팟 생성 및 참가 기능 구현

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/dto/response/UserInformationResponse.java
- src/main/java/com/api/stuv/domain/user/repository/UserCostumeRepository.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 버그 리스트, 빠진 내용 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #244 
- 남의 정보 조회 API에서 friendId 같이 보내주기
- 다른 사람이 작성한 게시글 목록 불러오기
- 내 게시글 목록 조회 createdAt null 값 수정하기
- 코스튬 수정 시 db 처리 오류 발생 에러
> [#244] API 버그 및 이슈 수정

- src/main/java/com/api/stuv/domain/friend/dto/FriendResponse.java
- src/main/java/com/api/stuv/domain/friend/entity/FriendFollowStatus.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- 검색시 PENDING 상태인 유저도 같이 검색
- 이 PR 이 해결하려는 관련 이슈 번호 : #241 
- 검색시 PENDING 상태인 유저도 같이 검색
> [#241] 유저 검색 수정

- src/main/java/com/api/stuv/domain/alert/dto/AlertResponse.java
- src/main/java/com/api/stuv/domain/alert/entity/Alert.java
- src/main/java/com/api/stuv/domain/alert/service/AlertService.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- Alert Response 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #253 
- Response 에 title 추가
- Response null 인 경우 제외
> [#253] Alert Response 수정

- src/main/java/com/api/stuv/domain/party/controller/PartyController.java
- src/main/java/com/api/stuv/domain/party/dto/response/PartyDetailResponse.java
- src/main/java/com/api/stuv/domain/party/dto/response/PointResponse.java
- src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepository.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- src/main/java/com/api/stuv/domain/user/entity/User.java
- src/main/java/com/api/stuv/domain/user/repository/PointHistoryRepository.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- src/main/java/com/api/stuv/global/util/scheduler/TimerScheduler.java
- 팟 인증 및 보상 획득 기능 구현
- 
- 이 PR 이 해결하려는 관련 이슈 번호 : #248 
- 팟 인증 기능
- 팟 보상 획득 기능
> [#248] 팟 인증 및 보상 획득 기능 구현

- src/main/java/com/api/stuv/domain/shop/controller/ShopController.java
- src/main/java/com/api/stuv/domain/shop/dto/costume/CostumeDTO.java
- src/main/java/com/api/stuv/domain/shop/dto/costume/CostumePurchaseRequest.java
- src/main/java/com/api/stuv/domain/shop/dto/costume/CostumeRandomRequest.java
- src/main/java/com/api/stuv/domain/shop/dto/costume/CostumeRandomResponse.java
- src/main/java/com/api/stuv/domain/shop/dto/costume/CostumeResponse.java
- src/main/java/com/api/stuv/domain/shop/dto/payments/PaymentConfirmRequest.java
- src/main/java/com/api/stuv/domain/shop/dto/payments/PaymentRequest.java
- src/main/java/com/api/stuv/domain/shop/dto/payments/PaymentResponse.java
- src/main/java/com/api/stuv/domain/shop/dto/payments/TossPaymentRequest.java
- src/main/java/com/api/stuv/domain/shop/dto/payments/TossPaymentResponse.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
- src/main/java/com/api/stuv/domain/shop/service/PaymentService.java
- costume, payments DTO 경로 구분
- s3service -> costumeservice
- querydsl : static import 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #249 
- costume, payments DTO 경로 구분하였습니다
- s3service 호출 위치 변경했습니다
> [#249] 코스튬 s3 리팩토링

- src/main/java/com/api/stuv/domain/auth/service/ReissueService.java
- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/global/service/RedisService.java
- src/main/resources/application.yml
- 코드 수정 및 리팩토링
- 이 PR 이 해결하려는 관련 이슈 번호 : #251
- 카카오 로그인 코드를 프론트에서 받아서 로그인하는 방식으로 변경
- reissue에서 토큰 재발급 시 레디스에 저장되어있는 refresh토큰과 쿠키에 저장되어있는 토큰 비교
> [#251] user refactoring

- src/main/java/com/api/stuv/domain/admin/controller/AdminController.java
- src/main/java/com/api/stuv/domain/admin/dto/request/EventPartyRequest.java
- src/main/java/com/api/stuv/domain/admin/dto/response/EventPartyResponse.java
- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/party/entity/PartyGroup.java
- src/main/java/com/api/stuv/domain/party/repository/confirm/QuestConfirmRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryCustom.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- src/test/java/com/api/stuv/domain/admin/service/AdminServiceTest.java
- 관리자 이벤트 팟 등록 및 조회하기
- 이 PR 이 해결하려는 관련 이슈 번호 : #260 
- 관리자 이벤트 팟 등록
- 관리자 이벤트 팟 목록 조회하기
> [#260] 관리자 이벤트 팟 등록 및 조회하기

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/dto/dto/BoardDetailDTO.java
- src/main/java/com/api/stuv/domain/board/dto/dto/BoardListDTO.java
- src/main/java/com/api/stuv/domain/board/dto/dto/CommentDTO.java
- src/main/java/com/api/stuv/domain/board/dto/request/BoardRequest.java
- src/main/java/com/api/stuv/domain/board/dto/request/BoardUpdateRequest.java
- src/main/java/com/api/stuv/domain/board/dto/request/CommentRequest.java
- src/main/java/com/api/stuv/domain/board/dto/response/BoardDetailResponse.java
- src/main/java/com/api/stuv/domain/board/dto/response/BoardIdResponse.java
- src/main/java/com/api/stuv/domain/board/dto/response/BoardResponse.java
- src/main/java/com/api/stuv/domain/board/dto/response/CommentResponse.java
- src/main/java/com/api/stuv/domain/board/entity/Board.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryCustom.java
- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryCustom.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/dto/dto/FriendListDTO.java
- src/main/java/com/api/stuv/domain/friend/dto/dto/FriendRecommendDTO.java
- src/main/java/com/api/stuv/domain/friend/dto/response/FriendFollowListResponse.java
- src/main/java/com/api/stuv/domain/friend/dto/response/FriendFollowResponse.java
- src/main/java/com/api/stuv/domain/friend/dto/response/FriendResponse.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/main/java/com/api/stuv/global/response/PageResponse.java
- src/test/java/com/api/stuv/domain/friend/service/AcceptFriendRequestTest.java
- 게시글 및 친구 리펙터링
- 이 PR 이 해결하려는 관련 이슈 번호 : #250 
- Repository 의 데이터 처리부를 Service 로 이전
> [#250] 게시글 및 친구 리펙터링

- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- 게시글 상세 조회 이미지 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #268 
- 게시글 상세 조회 이미지 변경
> [#268] 게시글 상세 조회 이미지 변경

- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- 코스튬 삭제 부분에 @transactional 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #278 
> [#278] 코스튬 삭제 트랜잭션 추가

- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/auth/service/CustomUserDetailsService.java
- src/main/java/com/api/stuv/domain/user/dto/response/LoginResponse.java
- 로그인 시 응답 값 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #277
- 로그인 시 role 값 함께 반환
> [#277] 로그인 응답 수정

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 에러 수정
- 
- 이 PR 이 해결하려는 관련 이슈 번호 : #281
- 카카오 로그인 응답 수정
- 내 정보 조회 고정 id 값 수정
> [#281] 카카오 로그인 응답 및 내 정보 조회 에러 수정

- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/party/repository/member/GroupMemberRepositoryImpl.java
- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- 관리자 팟 목록 및 인증 승인 화면 핫픽스
- 이 PR 이 해결하려는 관련 이슈 번호 : #285 
- 관리자 팟 목록 핫픽스
- 관리자 팟 인증 승인 화면 핫픽스
-
> [#285] 관리자 팟 목록 및 인증 승인 화면 핫픽스

- src/main/java/com/api/stuv/domain/auth/service/ReissueService.java
- src/main/java/com/api/stuv/domain/user/repository/UserRepositoryImpl.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- reissue status 코드 변경 및 이미지 출력 수정 
- 이 PR 이 해결하려는 관련 이슈 번호 : #284
> [#284] reissue status 코드 변경 및 이미지 출력 수정 

- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- 친구 검색 버그 픽스
- 친구 검색 버그 픽스
- 이 PR 이 해결하려는 관련 이슈 번호 : #289 
- 친구 검색 버그 픽스
> [#289] 친구 검색 픽스

- src/main/java/com/api/stuv/domain/board/repository/BoardRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- Board 및 Friend List 가져올 때 순서 createdAt 으로 정렬
- 이 PR 이 해결하려는 관련 이슈 번호 : #292 
- Board 및 Friend List 가져올 때 순서 createdAt 으로 정렬구현한 내용에 대한 자세한 설명
> [#292] 목록 조회 정렬

- src/main/java/com/api/stuv/global/config/SecurityConfig.java
- SecurityConfig에 https 주소 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #294
> [#294] SecurityConfig 수정

- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #297 
> [#297] kakao redirect uri 변경

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
- 읽음 처리 관련 방 세션 관리 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #299 
- 방 생성시에도 세션이 업데이트 하도록 수정
> [#299] 읽음 처리 관련 방 세션 관리 수정

- .github/workflows/cd.yml
- 사용하지 않는 도커 이미지, 컨테이너 볼륨 제거
- 이 PR 이 해결하려는 관련 이슈 번호 : #309 
- 메모리 부족 문제 해결을 위한 명령어 추가입니다
> [#309] docker 정리

- src/main/java/com/api/stuv/domain/auth/jwt/LoginFilter.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- url 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #312 
> [#312] SecurityConfig 및 카카오 로그인 수정

- .github/workflows/ci.yml
- build.gradle
- docker-compose.yml
- src/main/java/com/api/stuv/global/config/KafkaConfig.java
- src/main/resources/application.yml
- 옵저버빌리티 적용 전 기반 설정 적용 및 카프카 관련 설정 삭제
- 이 PR 이 해결하려는 관련 이슈 번호 : #106 
- 옵저버빌리티 적용 전 기반 설정 적용 및 카프카 관련 설정 삭제
> [#106] 옵저버빌리티 적용 전 기반 설정 적용 및 카프카 관련 설정 삭제

- src/main/java/com/api/stuv/domain/alert/dto/AlertEventDTO.java
- src/main/java/com/api/stuv/domain/alert/dto/AlertExpireDTO.java
- src/main/java/com/api/stuv/domain/alert/entity/Alert.java
- src/main/java/com/api/stuv/domain/alert/service/AlertService.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- src/main/java/com/api/stuv/global/service/RedisService.java
- src/main/java/com/api/stuv/global/util/common/TemplateUtils.java
- src/test/java/com/api/stuv/domain/board/service/ConfirmCommentTest.java
- Alert 기능 일부 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #317 
- 알림 읽음 -> 삭제 로직 변경
- 알림 삭제 스케쥴 10분으로 변경
- 알림 퍼블리싱을 비동기적으로 처리 -> 영속성 컨텍스트의 Transactional 로부터 분리
> [#317] Alert 기능 일부 수정

- src/main/java/com/api/stuv/domain/user/controller/UserController.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 로그인 여부 확인 기능 구현 및 회원 정보 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #321 
- 현재 로그인 되어있는 상태인지 확인하는 api 구현
- 비회원도 다른 회원에 대한 정보를 확인할 수 있도록 수정
> [#321] 로그인 여부 확인 기능 구현 및 회원 정보 수정

- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- 친구 목록 조회 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #326
- 친구 목록 조회 수정
> [#326] 친구 목록 조회 수정

- src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
- 로그아웃 시 에러 원인 log 설정
- 이 PR 이 해결하려는 관련 이슈 번호 : #328
> [#328] 로그아웃 시 에러 원인 log 설정

- src/main/java/com/api/stuv/domain/auth/jwt/CustomLogoutFilter.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #328 
> [#328] logout 에러 수정

- src/main/java/com/api/stuv/domain/admin/service/AdminService.java
- src/main/java/com/api/stuv/domain/party/service/PartyService.java
- src/main/java/com/api/stuv/global/exception/ErrorCode.java
- party 예외 추가 및 금액 차감 핫픽스
- 이 PR 이 해결하려는 관련 이슈 번호 : #332 
- party 예외 추가 및 금액 차감 핫픽스
> [#332] party 예외 추가 및 금액 차감 핫픽스

- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- 친구 아닌 회원 검색 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #334
> [#334] 친구 아닌 회원 검색 수정

- src/main/java/com/api/stuv/domain/alert/service/SseService.java
- sse 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #336
- sse 수정
> [#336] sse 수정

- src/main/java/com/api/stuv/domain/socket/dto/ChatMessageResponse.java
- src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
- 채팅 메세지 조회 readByCount 오류 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #337 
- 채팅 메세지 조회 readByCount 오류 수정
> [#337] 메세지 응답 오류 수정수정

- .gitignore
- build.gradle
- docker-compose.yml
- docker/grafana/config/grafana.ini
- docker/loki/config/local-config.yaml
- docker/prometheus/config/prometheus.yml
- docker/tempo/config/tempo.yaml
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- Observability 설정
- 이 PR 이 해결하려는 관련 이슈 번호 : #342 
- Tempo
- Grafana
- Prometheus
- Loki
- Nord Exporter
> [#342] Observability 설정

- src/main/java/com/api/stuv/domain/socket/controller/ChatController.java
- src/main/java/com/api/stuv/domain/socket/controller/ChatMessageController.java
- src/main/java/com/api/stuv/domain/socket/repository/ChatMessageRepositoryImpl.java
- src/main/java/com/api/stuv/domain/socket/service/ChatMessageService.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomDetailService.java
- src/main/java/com/api/stuv/domain/socket/service/ChatRoomMemberService.java
- src/main/java/com/api/stuv/global/config/RedisConfig.java
- 읽음 상태 업데이트 소켓 통신 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #322 
- Redis 캐시 적용 및 기존 ConcurrentMap 제거
- ChatRoomMemberService 활용하여 UserInfo Redis 캐시 적용
> [#322] 읽음 상태 업데이트 소켓 통신 변경

- docker-compose.yml
- 권한 관련 에러 핫픽스
- 이 PR 이 해결하려는 관련 이슈 번호 : #1
- 권한 관련 에러 핫픽스
> [#345] 도커 권한 관련 에러 핫픽스

- src/main/java/com/api/stuv/domain/board/controller/BoardController.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryCustom.java
- src/main/java/com/api/stuv/domain/board/repository/CommentRepositoryImpl.java
- src/main/java/com/api/stuv/domain/board/service/BoardService.java
- src/main/java/com/api/stuv/domain/friend/controller/FriendController.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryCustom.java
- src/main/java/com/api/stuv/domain/friend/repository/FriendRepositoryImpl.java
- src/main/java/com/api/stuv/domain/friend/service/FriendService.java
- 게시판 및 친구 일부 기능 페이지네이션 제거
- 이 PR 이 해결하려는 관련 이슈 번호 : #349
- 게시판 댓글 목록
- 친구 요청 목록
- 친구 목록
> [#349] 게시판 및 친구 일부 기능 페이지네이션 제거

- src/main/java/com/api/stuv/domain/party/repository/party/PartyGroupRepositoryImpl.java
- src/main/resources/application.yml
- 참여중인 팟 목록에서 인원수가 잘못 나오는 버그 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #350 
- 참여중인 팟 목록에서 인원수가 잘못 나오는 버그 수정
> [#350] 참여중인 팟 목록에서 인원수가 잘못 나오는 버그 수정

- src/main/java/com/api/stuv/global/service/RedisService.java
- 알림 삭제 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #358 
- 알림 삭제 수정
> [#358] 알림 삭제 수정

- deploy.sh
- 컨테이너 상태 확인 수정
- 이 PR 이 해결하려는 관련 이슈 번호 : #323 
- 컨테이너 상태 확인 수정
> fix: 컨테이너 상태 확인 수정

- docker/proxy/nginx.conf
- 사용자명 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #323 
- nginx 수정
> [#323] nginx 사용자 변경

- deploy.sh
- nginx 이미지 버전에 맞는 명령어 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #323 
- nginx 명령어 변경
> [#323] nginx 내부 명령어 변경

- docker/prometheus/config/prometheus.yml
- 이 PR 이 해결하려는 관련 이슈 번호 : #fix
> [#fix] 블루그린 배포에 맞춰 수집기 설정 변경

- docker-compose.yml
- 옵저버빌리티 ec2 내부 데이터 저장 디렉토리 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #fix
- 옵저버빌리티 ec2 내부 데이터 저장 디렉토리 변경
> [#fix] 옵저버빌리티 ec2 내부 데이터 저장 디렉토리 변경

- src/main/java/com/api/stuv/domain/shop/controller/ShopController.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryCustom.java
- src/main/java/com/api/stuv/domain/shop/repository/CostumeRepositoryImpl.java
- src/main/java/com/api/stuv/domain/shop/service/CostumeService.java
- 코스튬 목록 조회 페이지네이션 제거
- 이 PR 이 해결하려는 관련 이슈 번호 : #372 
- 페이지네이션 목록 조회 리팩토링
> [#372] 코스튬 목록 조회 리팩토링

- src/main/resources/application.yml
- 파일 용량 제한 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #hotfix
- 파일 용량 제한 변경
> [#hotfix] 파일 용량 제한 변경

- deploy.sh
- nginx 오류 수정
- 배포 서버 실행 대기 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #374 
- 설정 파일 수정
> [#374] 배포 서버 실행 대기

- deploy.sh
- 서버 배포까지 실행 대기 시간 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #374 
- 배포 서버 실행 대기 시간 증가 테스트
> [#374] 배포 서버 실행 시간 수정

- README.md
- 이 PR 이 해결하려는 관련 이슈 번호 : #371 
> [#371]README 편집

- deploy.sh
- 사용하지 않는 이미지 삭제 명령어 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #374 
- 사용하지 않는 이미지 삭제 명령어 추가
> [#374] 사용하지 않는 docker 정리

- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
- 이 PR 이 해결하려는 관련 이슈 번호 : #383 
> [#383] 카카오 로그인 버그 수정

- src/main/java/com/api/stuv/domain/user/repository/UserRepository.java
- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
> [#383] 카카로 회원가입 버그 수정

- src/main/java/com/api/stuv/domain/user/service/KakaoService.java
> [#383] kakao login 버그 수정

- src/main/java/com/api/stuv/domain/user/entity/User.java
- src/main/java/com/api/stuv/domain/user/service/UserService.java
- 일반 회원가입을 한 사람이 소셜 로그인을 원한다면 소셜 로그인 연결해주는 기능 구현
- 이 PR 이 해결하려는 관련 이슈 번호 : #389 
> [#389] 일반 회원가입 소셜 회원가입 연결

- src/main/resources/application.yml
- 카카오 redirect-uri 변경
- 이 PR 이 해결하려는 관련 이슈 번호 : #391 
> [#391] 카카오 redirect-uri 변경

- src/main/java/com/api/stuv/domain/image/service/ImageService.java
- webp 추가
- 이 PR 이 해결하려는 관련 이슈 번호 : #393 
- 이미지 확장자 추가했습니다
> [#393] 이미지 확장자 추가
